releases:
  -
    version:
    mongodb:
      server:
        version:
        link:
      tools:
        version:
        link:
    migrations:
      pre:
        - some
        - -some
    epoch:

  -
