#
# Easiest way to work with this file, from an updated Ubuntu 16.04 LTS image
# 1.   create a non-root user with sudo priv and perform following steps as non-root
# 2.  `sudo apt-get update`
# 3.  `sudo apt-get install snapcraft python build-essential`
# 4.  `snapcraft stage`
# 5.  `snapcraft snap`

name: rocketchat-server
version: ROCKET_CHAT_BUILD_VERSION
summary: Rocket.Chat server
description: Have your own Slack like online chat, built with Meteor. https://rocket.chat/
confinement: strict
base: core
assumes: [snapd2.21]
apps:
    rocketchat-server:
        command: startRocketChat
        daemon: simple
        after: [rocketchat-mongo-daemon]
        plugs: [network, network-bind, removable-media]
    rocketchat-mongo-daemon:
        command: mongo.sh --start
        stop-command: mongo.sh --stop
        daemon: forking
        plugs:
            - network
            - network-bind
            - network-observer
    rocketchat-mongo:
        command: mongo.sh --logs
        stop-command: mongo.sh --stop
        after: [rocketchat-mongo-daemon]
        daemon: simple
    rocketchat-caddy:
        command: env LC_ALL=C caddy -conf=$SNAP_DATA/Caddyfile
        daemon: simple
        plugs: [network, network-bind]
    mongo:
        command: mongo.sh
        plugs: [network]
    restoredb:
        command: env LC_ALL=C restoredb
        plugs: [network]
    backupdb:
        command: env LC_ALL=C backupdb
        plugs: [network]
    initcaddy:
        command: env LC_ALL=C initcaddy
hooks:
    configure:
        plugs: [network]
    pre-refresh:
        plugs: [network]
parts:
    node:
        plugin: dump
        source: ./
        override-build: ./resources/preparenode
        build-environment:
            - node_version: v12.22.1
        build-packages:
            # For fibers
            - python
            - build-essential
            - nodejs
        stage:
            - bin
            - include
            - share
            - lib
    rocketchat-server:
        build-packages:
            - curl
        plugin: dump
        override-build: ./resources/prepareRocketChat
        after: [node]
        source: ./
        stage-packages:
            - execstack
            - fontconfig-config
        stage:
            - programs
            - main.js
            - .node_version.txt
            - etc
            - usr
            - star.json
    mongodb:
        build-packages:
            - wget
        source: ./
        override-build: ./resources/preparemongo
        plugin: dump
        stage-packages:
            - libssl1.0.0
        prime:
            - usr
            - bin
            - lib
    scripts:
        plugin: dump
        source: ./resources/
        source-type: local
        organize:
            backupdb: bin/backupdb
            restoredb: bin/restoredb
            mongo.sh: bin/mongo.sh
            startRocketChat: bin/startRocketChat
            initreplset.js: bin/initreplset.js
            Caddyfile: bin/Caddyfile
            initcaddy: bin/initcaddy
        prime:
            - bin
    caddy:
        override-build: ./resources/preparecaddy
        plugin: dump
        source: ./
        prime:
            - bin
        organize:
            caddy: bin/caddy
        after: [mongodb]
    hooks:
        plugin: nil
        stage-packages:
            - dnsutils
            - curl
        prime:
            - usr
            - lib

