apps:
  backupdb:
    command: bin/backupdb.sh
    environment:
      LC_ALL: C
    plugs:
    - network
  mongo:
    command: usr/bin/mongosh
    environment:
      LC_ALL: C
    plugs:
    - network
  mongosh:
    command: usr/bin/mongosh
    environment:
      LC_ALL: C
    plugs:
    - network
  restoredb:
    command: bin/restoredb.sh
    environment:
      LC_ALL: C
    plugs:
    - network
  rocketchat-caddy:
    command: bin/start_caddy.sh
    daemon: simple
    environment:
      LC_ALL: C
    install-mode: disable
    plugs:
    - network
    - network-bind
  rocketchat-mongo:
    command: bin/start_mongod.sh
    daemon: forking
    environment:
      LC_ALL: C
    plugs: &id001
    - network
    - network-bind
    - network-observe
    - mount-observe
    - system-observe
    stop-command: bin/stop_mongod.sh
  rocketchat-server:
    after:
    - rocketchat-mongo
    command: bin/start_rocketchat.sh
    daemon: simple
    environment:
      DEPLOY_METHOD: snap
      LC_ALL: C
    plugs:
    - network
    - network-bind
    - removable-media
    stop-command: bin/stop_rocketchat.sh
base: core22
confinement: strict
description: 'Have your own Slack like online chat, built with Meteor. https://rocket.chat/

  '
epoch: 11*
grade: stable
hooks:
  configure:
    plugs:
    - network
    - network-bind
  install:
    plugs: *id001
  post-refresh:
    plugs: *id001
  pre-refresh:
    plugs: *id001
name: rocketchat-server
parts:
  caddyv1:
    organize:
      caddy: bin/caddy1
    plugin: dump
    source:
    - on amd64: 
        https://github.com/caddyserver/caddy/releases/download/v1.0.4/caddy_v1.0.4_linux_amd64.tar.gz
    - on arm64: 
        https://github.com/caddyserver/caddy/releases/download/v1.0.4/caddy_v1.0.4_linux_arm64.tar.gz
    stage:
    - ./*
    - -README.txt
    - -LICENSES.txt
    - -CHANGES.txt
    - -init
  caddyv2:
    organize:
      caddy: bin/caddy2
    plugin: dump
    source:
    - on amd64: 
        https://github.com/caddyserver/caddy/releases/download/v2.4.3/caddy_2.4.3_linux_amd64.tar.gz
    - on arm64: 
        https://github.com/caddyserver/caddy/releases/download/v2.4.3/caddy_2.4.3_linux_arm64.tar.gz
    stage:
    - ./*
    - -README.md
    - -LICENSE
  commands:
    organize:
      '*': bin/
    plugin: dump
    source: ./commands
  daemons:
    organize:
      '*': bin/
    plugin: dump
    source: ./daemons
  deno:
    organize:
      deno: bin/deno
    plugin: dump
    source:
    - on amd64: 
        https://github.com/denoland/deno/releases/download/v1.37.1/deno-x86_64-unknown-linux-gnu.zip
    source-type: zip
  helper-dependencies:
    plugin: nil
    stage-packages:
    - jq
  helpers:
    organize:
      '*': helpers/
    plugin: dump
    source: ./helpers/
  migrations:
    organize:
      '*': migrations/
    plugin: dump
    source: ./migrations
    stage-packages:
      - python3-ruamel.yaml
      - python3
  mongodb-libssl-backwards-compat:
    plugin: dump
    source: 
      https://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
    source-checksum: 
      sha256/7cf39d70a639017d1dd7c8d36daa2258063608688e449fddf40ffdd46f992a78
    source-type: deb
  mongodb-tools:
    plugin: dump
    source:
    - on amd64: 
        https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.10.0.tgz
    stage:
    - bin/mongodump
    - bin/mongorestore
  mongosh:
    plugin: dump
    source: 
      https://downloads.mongodb.com/compass/mongodb-mongosh_2.3.3_amd64.deb
    source-type: deb
  rocketchat:
    after:
    - rocketcraft
    build-packages:
    - build-essential
    override-build: '(cd programs/server; npm i --omit=dev --unsafe-perm)

      snapcraftctl build

      '
    plugin: dump
    source: https://releases.rocket.chat/$SNAPCRAFT_PROJECT_VERSION/download
    source-type: tar
    stage:
    - ./*
    - ./.node_version.txt
    - -README
    - -README.md
    - -LICENSE
    - -CHANGELOG.md
    - -share
    stage-packages:
    - fontconfig
  rocketcraft:
    build-packages:
    - python3
    - python3-venv
    - python3-apt
    override-build: 'cd $CRAFT_PART_BUILD

      python3 -m venv .venv

      source .venv/bin/activate

      pip install -r requirements.txt


      # ./rocketcraft parts prime --parts-file /root/parts/rocketcraft/build/parts-*.yaml
      --work-dir /root/parts/rocketcraft/build/work --cache-dir /root/parts/rocketcraft/build/cache

      ./rocketcraft parts prime --parts-file $CRAFT_PART_BUILD/parts-$SNAPCRAFT_PROJECT_VERSION.yaml
      --work-dir $CRAFT_PART_BUILD/work --cache-dir $CRAFT_PART_BUILD/cache


      cp -rp $CRAFT_PART_BUILD/work/prime/* $CRAFT_PART_INSTALL/

      '
    plugin: dump
    source: ./rocket_craft
  yq:
    organize:
      yq_linux_*: bin/yq
    plugin: dump
    source:
    - on amd64: 
        https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_amd64.tar.gz
    - on arm64: 
        https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_arm64.tar.gz
    stage:
    - bin
summary: An Open Source Slack Alternative
title: Rocket.Chat Server
version: 7.13.5
