name: Update snap release

on:
  workflow_dispatch:

jobs:
  BuildAndRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run action
        uses: .
