name: Update helm chart

on:
  release:
    types: [published]

jobs:
  release_snap_amd64:
    # Obs: tracks can’t be opened dynamically. We have to explicitly open them by request when a new major version gets released, otherwise this task will fail.
    env:
      SNAPCRAFT_REPO: RocketChat/rocketchat-server-snap
      TESTS_REPO: RocketChat/rocketchat-release-tests
    runs-on: ubuntu-18.04
    needs: deploy
    if: github.event_name == 'release'
    steps:
      - name: Parse environment variables
        run: |
          export ROCKETCHAT_VERSION=${{ github.event.release.tag_name }}
          echo "SNAP_TRACK=${ROCKETCHAT_VERSION:0:1}.x" >> $GITHUB_ENV
          echo "ROCKETCHAT_VERSION=$ROCKETCHAT_VERSION" >> $GITHUB_ENV
          [[ -z "$(echo ${{ env.ROCKETCHAT_VERSION }} | grep rc)" ]] && echo "CANDIDATE=false" >> $GITHUB_ENV

      - name: Clone snapcraft repo
        if: env.CANDIDATE == 'false'
        uses: actions/checkout@v2
        with:
          repository: "${{ env.SNAPCRAFT_REPO }}"
      
      - name: Clone tests repo
        uses: actions/checkout@v2
        with:
          repository: "${{ env.TESTS_REPO }}"
          path: './test_scripts'
          
        id: version
      - name: Set build version 
        run: sed -i -r '/^version:/ s/ .+/ ${{ env.ROCKETCHAT_VERSION }}/' ./snap/snapcraft.yaml
      
      - name: Build snap
        uses: snapcore/action-build@v1
        id: build
        with:
          path: "."
      
      - name: Install and test the generated snap
        run: ./test_scripts/snap_install_test.sh ${{ steps.build.outputs.snap }}
      
      - name: Remove snap
        run: sudo snap remove rocketchat-server
      
      - name: Publish snap to edge channel
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPCRAFT_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: ${{ env.SNAP_TRACK }}/edge
      
      - name: Test snap updating
        run: ./test_scripts/snap_update_test.sh
      
      - name: Promote edge to candidate
        run: |
          echo "${{ secrets.SNAPCRAFT_LOGIN }}" | snapcraft login --with -
          REVISION=$(snapcraft list-revisions rocketchat-server --arch amd64 | grep $SNAP_TRACK/edge | cut -d' ' -f 1 | head -n 1)
          snapcraft release rocketchat-server $REVISION $SNAP_TRACK/candidate
      
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
        if: env.CANDIDATE == 'false'
        continue-on-error: true
        with:
          type: ${{ job.status }}
          job_name: '*Snapcraft build*'
          mention: 'here'
          mention_if: 'failure'
          url: ${{ secrets.RELEASE_IMAGES_ROCKETCHAT_WEBHOOK }}