name: Build, test and release snap

description: Always do what the title says, irrespective of how being called

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      snapcraft-credential:
        required: true
      github-token:
        required: true
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false

env:
  REPO: RocketChat/server-snap

jobs:
  prereqs:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}

      - shell: bash
        id: version
        run: |
          tag="${{ inputs.tag }}"

          if [[ -z "$tag" ]]; then # like in case of workflow_dispatch with no tag set
            tag="$(awk -F: '/^version:/ {print $2}' snap/snapcraft.yaml | tr -d '[:space:]')"
          else
            tag="${{inputs.tag}}"
          fi

          echo "tag: $tag"
          echo "version=$tag" >> $GITHUB_OUTPUT

      - uses: debdutdeb/semis@main

      - shell: bash
        name: make sure an older version do not get pushed over current release
        run: |
          # Snap will just push a new revision over current, so, no
          current="$(awk -F: '/^version:/ {print $2}' snap/snapcraft.yaml | tr -d '[:space:]')"

          if semis gt $current ${{ steps.version.outputs.version }}; then
            echo "$current is higher than given version, exiting"
            exit 1
          fi

  build:
    needs: [ prereqs ]
    uses: RocketChat/server-snap/.github/workflows/build.yml@develop
    with:
      tag: ${{ needs.prereqs.outputs.version }}

  test:
    needs: [ build, prereqs ]
    uses: RocketChat/server-snap/.github/workflows/test.yml@develop
    with:
      tag: ${{ needs.prereqs.outputs.version }}
      artifact-key: ${{ needs.build.outputs.snap-artifact-key}}
      snap-basename: ${{needs.build.outputs.snap-basename }}
    secrets:
      snapcraft-credential: ${{secrets.snapcraft-credential || secrets.SNAPCRAFT_STORE_CREDENTIALS }}

  release:
    if: '! contains(inputs.tag, ''rc'')'
    needs:
      - build
      - test
    uses: RocketChat/server-snap/.github/workflows/release.yml@develop
    with:
      snap-basename: ${{ needs.build.outputs.snap-basename }}
      tag: ${{ inputs.tag }}
      snap-artifact-key: ${{ needs.build.outputs.snap-artifact-key }}
    secrets:
      snapcraft-credential: ${{ secrets.snapcraft-credential || secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      github-token: ${{ secrets.github-token || secrets.GH_TOKEN_PERSONAL }}
