name: Release snap (reusable)

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      snap-basename:
        required: true
        type: string
      snap-artifact-key:
        required: true
        type: string
      run-id:
        type: string # this needs to be string here, since apparently inputs.run-id in caller is sending a string, action converts back to int
        required: false
    secrets:
      snapcraft-credential:
        required: true
      snapcraft-key:
        required: true
      snapcraft-key-passphrase:
        required: true
      github-token:
        required: true

env:
  REPO: RocketChat/server-snap


jobs:
  publish-snap:
    env:
      ROCKETCHAT_SNAP: ${{ format('/tmp/{0}', inputs.snap-basename) }}
    runs-on: ubuntu-latest
    outputs:
      track: ${{ steps.track.outputs.track }}
    steps:
      - id: track
        run: |
          tag=${{inputs.tag}}
          track=${tag:0:1}.x
          echo "track: $track"
          echo "track=$track" >> $GITHUB_OUTPUT

      - name: Download snap from another run-id
        uses: actions/download-artifact@v4
        if: inputs.run-id != ''
        with:
          repository: RocketChat/server-snap
          name: ${{ inputs.snap-artifact-key }}
          path: /tmp
          run-id: ${{ inputs.run-id }}
          github-token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }} # https://github.com/actions/download-artifact/blob/7fba95161a0924506ed1ae69cdbae8371ee00b3f/src/download-artifact.ts#L42-L52

      - name: Download snap
        uses: actions/download-artifact@v4
        if: inputs.run-id == ''
        with:
          repository: RocketChat/server-snap
          name: ${{ inputs.snap-artifact-key }}
          path: /tmp

      - uses: samuelmeuli/action-snapcraft@v2
        name: 'Install snapcraft'

      - run: |
          ls /tmp
          snap_file=${ROCKETCHAT_SNAP}
          test -f $snap_file
          test -f ~/.snap/gnupg || mkdir -p ~/.snap/gnupg
          echo "${{ secrets.snapcraft-key }}" | gpg --batch --import
          snapcraft sign-build $snap_file --key-name snapcraft-builds --passphrase ${{ secrets.snapcraft-key-passphrase }}
          assertion=${snap_file%%.snap}.ack
          test -f $assertion
          echo "assertion=$assertion"
        id: assertion
        
      - name: 'Create release with artifact'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ROCKETCHAT_SNAP }}
            ${{ steps.assertion.outputs.assertion }}
          prerelease: false
          repository: ${{ env.REPO }}
          token: ${{ secrets.github-token }}
          name: ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          body: ${{ format('https://github.com/RocketChat/Rocket.Chat/releases/{0}', inputs.tag) }}
          draft: false
          fail_on_unmatched_files: true
          target_commitish: ${{steps.track.outputs.track}}
          generate_release_notes: true

      - name: 'Upload to snapstore'
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft-credential }}
        with:
          snap: ${{ env.ROCKETCHAT_SNAP }}
          release: ${{ format('{0}/stable', steps.track.outputs.track) }}

  repo-actions:
    runs-on: ubuntu-latest
    needs:
      - publish-snap
    steps:
      - name: 'Clone snap repo'
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          ref: ${{needs.publish-snap.outputs.track}}

      - uses: debdutdeb/semis@main

      - shell: bash
        id: commit
        run: |
          current="$(awk -F: '/^version:/ {print $2}' snap/snapcraft.yaml | tr -d '[:space:]')"
          if semis gt ${{ inputs.tag }} $current; then
            echo "committing"
            echo "commit=true" >>$GITHUB_OUTPUT
            sed -i -r '/^version:/ s/ .+/ ${{ inputs.tag }}/' ./snap/snapcraft.yaml
          fi

      - name: 'Commit snapcraft file'
        if: steps.commit.outputs.commit == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          add: ./snap/snapcraft.yaml
          message: 'Bump Rocket.Chat version to ${{ inputs.tag }}'
          push: true
