name: Release snap

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      snap:
        required: true
        type: string
      snap-track:
        required: true
        type: string
      commit:
        required: true
        type: string
    secrets:
      snapcraft-credential:
        required: true
      github-token:
        required: true

env:
  REPO: RocketChat/server-snap


jobs:
  publish-snap:
    env:
      ROCKETCHAT_SNAP: ${{ format('/tmp/{0}', inputs.snap) }}
    runs-on: ubuntu-latest
    steps:
      - name: Download snap
        uses: actions/download-artifact@v3
        with:
          name: snap
          path: /tmp

      - name: 'Upload to snapstore'
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft-credential }}
        with:
          snap: ${{ env.ROCKETCHAT_SNAP }}
          release: ${{ format('{0}/edge', inputs.snap-track) }}

      - name: 'Create release with artifact'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ROCKETCHAT_SNAP }}
          prerelease: false
          repository: ${{ env.REPO }}
          token: ${{ secrets.github-token }}
          name: ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          body: ${{ format('https://github.com/RocketChat/Rocket.Chat/releases/{0}', inputs.tag) }}
          draft: false
          fail_on_unmatched_files: true
          target_commitish: ${{ inputs.snap-track}}
          generate_release_notes: true

  repo-actions:
    runs-on: ubuntu-latest
    needs:
      - publish-snap
    if: "${{ inputs.commit == 'true' }}"
    steps:
      - name: 'Clone snap repo'
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          token: ${{ secrets.github-token }}
          ref: ${{inputs.snap-track}}

      - name: 'Update version'
        shell: bash
        run: sed -i -r '/^version:/ s/ .+/ ${{ inputs.tag }}/' ./snap/snapcraft.yaml

      - name: 'Commit snapcraft file'
        uses: EndBug/add-and-commit@v9
        with:
          add: ./snap/snapcraft.yaml
          message: 'Bump Rocket.Chat version to ${{ inputs.tag }}'
          push: true
