name: Test snap (reusable)
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      snap-artifact-key:
        required: true
        type: string
      snap-basename:
        required: true
        type: string
      run-id:
        type: string
        required: false
    secrets:
      snapcraft-credential:
        required: true

jobs:
  can-i-run:
    env:
      ROCKETCHAT_SNAP: ${{ format('/tmp/{0}', inputs.snap-basename) }}
    runs-on: ubuntu-latest
    steps:
      - name: Download snap
        if: inputs.run-id == ''
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.snap-artifact-key }}
          path: /tmp

      - name: Download snap from other workflow run
        if: inputs.run-id != ''
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run-id }}
          path: /tmp

      - name: 'Clone tests repository'
        uses: actions/checkout@v3
        with:
          repository: RocketChat/public-releases
          submodules: true

      - uses: samuelmeuli/action-snapcraft@v2
        name: 'Install snapcraft'

      - id: track
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft-credential }}
        shell: bash
        run: |
          track=${{ inputs.tag }}
          track=${track:0:1}.x
          if ! snapcraft list-revisions rocketchat-server | tail -n '+2' | grep -q "$track/stable"; then
            last_channel="$((${track:0:1}-1)).x/stable"
          fi

          echo "last_channel: $last_channel"
          echo "last-channel=$last_channel" >> $GITHUB_OUTPUT

      - name: 'Run tests'
        shell: bash
        env:
          ROCKETCHAT_PREVIOUS_CHANNEL: ${{ steps.track.outputs.last-channel}}
          ROCKETCHAT_TAG: ${{ inputs.tag }}
        run: |
          sudo apt-get --no-install-recommends install jo jq -y
          bash ./run_snap.bash

