#! /bin/bash

source $SNAP/helpers/environment.sh

exec_post_refresh_scripts() {
    find $SNAP/migrations -executable -type f -regex '.+/post_.+' | while read script; do (source $script; start) || error "post refresh migration \"${script#$SNAP/migrations/*post_}\" run failed"; done
}

main() {
    exec_post_refresh_scripts
}

main
