#! /bin/bash

source $SNAP/helpers/environment.sh

backup_if_enabled() {
  [[ $(snapctl get backup-on-refresh) == "enable" ]] && {
    backupdb.sh || {
      echo "failed to backup rocketchat database before refresh" \
        > $SNAP_COMMON/refresh_$(date +"%Y%m%d.%H%M").log
    }
  }
}

exec_pre_refresh_scripts() {
  find $SNAP/migrations -executable -type f -regex '.+/pre_.+' | while read script; do (source $script; start) || error "pre refresh migration \"${script#$SNAP/migrations/*pre_}\" run failed"; done
}

main() {
  backup_if_enabled
  exec_pre_refresh_scripts
}

main
