#! /bin/bash

export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu"
export LD_LIBRARY_PATH=$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH

TIMESTAMP=$(date +"%Y%m%d.%H%M")

[[ $(snapctl get backup-on-refresh) == "enable" ]] && backupdb

(( $? )) && echo "failed to backup rocketchat database before refresh" > $SNAP_COMMON/refresh_$TIMESTAMP.log
